local_costmap:
   global_frame: odom_combined
   robot_base_frame: base_footprint
   publish_voxel_map: true
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.025
   transform_tolerance: 0.5
   origin_x: 0.0
   origin_y: 0.0
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
